### ISSUE TITLE
addGroup()

### ISSUE THREAD

**Issue by stewartoallen** [vasturiano/three-fatline#11]
Does LineSegments2 not support the `addGroup` api inherited from BufferGeometry? If not, how are disjoint line regions with different colors supported?

I'm attempting to use LineGeometry, LineSegment2, and LineMaterial as drop in replacements when rendering lines from existing code that uses BufferGeometry, LineSegments, and LineBasicMaterial. Thanks

**Comment by stewartoallen** [comment]
digging into the code further, I see it's using a totally different set of buffers. I will test further because I need to have transparent/invisible gaps between discrete closed polylines ordering in the 10s or 100s of thousands and thus multiple geometries isn't a suitable alternative because it does not scale.

I would like to be able to commit to using this in my code rather than stock the stock lines, because it just looks so much better. will this be mainlined at some point? my concern is that it becomes incompatible with the core geometry at some point.

thanks again

**Comment by vasturiano** [comment]
Hi @stewartoallen, thanks for reaching out.

I'd like to mention that this is a modularized version of [this source code that lives in the ThreeJS repo](https://github.com/mrdoob/three.js/tree/master/examples/js/lines). So, it's probably worth reiterating your questions in that repo to get better anwers.
