### ISSUE TITLE
Can't find a license

### ISSUE THREAD

**Issue by hyandell** [vasturiano/three-fatline#13]
Hi Vasco,

I wasn't able to find a license for this project. Do you have a license in mind for folk to be able to use the code?

**Comment by vasturiano** [comment]
@hyandell as mentioned in the readme, this is a modularized version of this example from the [three.js repo](https://github.com/mrdoob/three.js): https://github.com/mrdoob/three.js/tree/master/examples/js/lines

So, it just follows the same license (MIT) as ThreeJS: https://github.com/mrdoob/three.js/blob/dev/LICENSE

**Comment by hyandell** [comment]
Thank you Vasco.
