### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by coreymartin** [vasturiano/three-fatline#19]
Hi there, thank you very much for the amazing work on this and three-globe! Would it be possible to add the same license here as for three-globe?

**Comment by coreymartin** [comment]
@vasturiano Mind if I open a PR to add the license?

**Comment by RoboTricker** [comment]
@vasturiano Thanks for creating this project!
I'd also appreciate a generous license.

**Comment by SarojiOS** [comment]
@vasturiano @phocks @performonkey @rickardcreatics @coreymartin  Your globe.gl library is amazing. Request you kindly add the same license for three-fatline also.

**Comment by vasturiano** [comment]
@SarojiOS thanks for reaching out. `three-fatline` is no longer a dependency of `three-globe`.
