### ISSUE TITLE
update shaders to support initial gap offset

### ISSUE THREAD

**Issue by lslzl3000** [vasturiano/three-fatline#4]
I added a new issue in Three.js for asking updates in LineMaterial, thanks for [Mugen87](https://github.com/Mugen87), he added a new offset parameter very soon(it's actually a very simple change😂 ). I think we could enable animation for flatline now.

dev update:
https://github.com/mrdoob/three.js/blob/e2c5134bb46ea2bce3e1b1743335f1b11d9070e2/examples/js/lines/LineMaterial.js#L212

**Comment by vasturiano** [comment]
@lslzl3000 that's awesome! I've patched this repo with `dashOffset` addition and will integrate it with the globe component so that it will be possible to animate dashed fatlines. 👍
