### ISSUE TITLE
flatline unable to catch event with raycaster

### ISSUE THREAD

**Issue by lslzl3000** [vasturiano/three-fatline#7]
Try this demo https://codepen.io/ShuangLiu/pen/MWvYBLq
pathStroke(2) enable flatline, but unable to catch event with raycaster

**Comment by lslzl3000** [comment]
the latest three example should fix this problem
https://github.com/vasturiano/three-fatline/blob/cf750156d42888d3f1f87c3b01736d93db2463de/src/LineSegments2.js#L215-L216

it should be
```
_start4.w = 1;
_end4.w = 1;  // camera space 
```

**Comment by vasturiano** [comment]
Thanks for the report @lslzl3000. I've updated the code to the latest version, which should fix this issue if you pull the latest version of this module.
